site_name: SIMPLOO Documentation
site_description: Simple Lua Object Orientation - A class-based OOP library for Lua
site_url: https://github.com/maurits150/simploo
repo_url: https://github.com/maurits150/simploo
repo_name: maurits150/simploo

theme:
  name: material
  features:
    - content.tabs.link
    - content.code.copy
    - navigation.sections
    - navigation.expand
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Guide:
    - Classes: guide/classes.md
    - Members: guide/members.md
    - Constructors: guide/constructors.md
    - Instances: guide/instances.md
    - Access Control: guide/access-control.md
    - Statics: guide/statics.md
    - Inheritance: guide/inheritance.md
    - Polymorphism: guide/polymorphism.md
    - Interfaces: guide/interfaces.md
    - Namespaces: guide/namespaces.md
    - Null Values: guide/null-values.md
  - Features:
    - Metamethods: features/metamethods.md
    - Serialization: features/serialization.md
    - Hotswap: features/hotswap.md
  - Reference:
    - Configuration: reference/config.md
    - Hooks: reference/hooks.md
    - Instance Methods: reference/instance-methods.md
    - Modifiers: reference/modifiers.md
